name: Lint

# Run this workflow every time a new commit pushed to your repository
on: 
  - push
  - pull_request

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run-linters:
    # Name the Job
    name: Run Linters
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
        
      - name: install node.js dependencies
        run: npm install
       
            
      
        
      - name: Run Linter
        run: make lint

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          
